// Ported from FlexLayout (https://github.com/caplin/FlexLayout), scripts/generate-json-interfaces.ts.
// Copyright (c) 2017 Caplin Systems Ltd. MIT licence, see LICENSE.
//
// Regenerates the attribute interfaces at the bottom of src/model/IJsonModel.ts from the
// attribute definitions, formatted with Biome. `--check` fails instead of writing when the
// committed file is out of date.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { runnerImport } from "vite";

const file = fileURLToPath(
    new URL("../src/model/IJsonModel.ts", import.meta.url),
);
const src = readFileSync(file, "utf8");

// the model sources use extensionless relative imports, which Node's own type stripping cannot
// resolve, so the model is loaded through Vite's module runner
const { module } = await runnerImport<typeof import("../src/model/Model")>(
    fileURLToPath(new URL("../src/model/Model.ts", import.meta.url)),
);
const { Model } = module;

const marker = "// below this line is autogenerated";
const markerIndex = src.indexOf(marker);
if (markerIndex === -1) {
    throw new Error(
        `Could not find the autogenerated marker comment in ${file}`,
    );
}
const bannerEnd = src.indexOf("\n", markerIndex);
const secondBannerEnd = src.indexOf("\n", bannerEnd + 1);
const header = src.slice(0, secondBannerEnd + 1);

const generated = `${header + Model.toTypescriptInterfaces()}\n`;
const formatted = execFileSync(
    "biome",
    ["format", `--stdin-file-path=${file}`],
    {
        input: generated,
        encoding: "utf8",
    },
);

if (process.argv.includes("--check")) {
    if (formatted !== src) {
        console.error(
            "src/model/IJsonModel.ts is out of sync with the attribute definitions.\nRun `pnpm --filter @fragiola/dockable generate:interfaces` to regenerate it.",
        );
        process.exit(1);
    }
    console.log("src/model/IJsonModel.ts is up to date.");
} else {
    writeFileSync(file, formatted);
    console.log("Regenerated src/model/IJsonModel.ts");
}
