// Generates the examples manifest before `next dev` / `next build`:
//
//   examples/manifest.generated.ts   slugs, metas, file lists (server and client)
//   examples/loaders.generated.ts    slug → lazy import of the example (client)
//
// Both are git-ignored; they are rebuilt on every dev start, build and
// typecheck, so they cannot go stale in a commit.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { EXAMPLES_DIR, loadExamples } from "./examples-lib.ts";

const HEADER =
    "// Generated by scripts/build-examples.ts. Do not edit; it is git-ignored.\n";

const examples = await loadExamples();

writeFileSync(
    join(EXAMPLES_DIR, "manifest.generated.ts"),
    `${HEADER}
import type { ExampleEntry } from "./entry-types";

export const EXAMPLES: ExampleEntry[] = ${JSON.stringify(examples, null, 4)};
`,
);

writeFileSync(
    join(EXAMPLES_DIR, "loaders.generated.ts"),
    `${HEADER}
import type { ComponentType } from "react";

export const LOADERS: Record<string, () => Promise<{ default: ComponentType }>> = {
${examples.map((e) => `    ${JSON.stringify(e.slug)}: () => import("./${e.slug}"),`).join("\n")}
};
`,
);

console.log(
    `examples: ${examples.length} (${examples.map((e) => e.slug).join(", ")})`,
);
